# Generated by Django 4.2.8 on 2024-01-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myoffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsin_id', models.CharField(db_index=True, max_length=255)),
                ('image_url', models.URLField(db_index=True)),
                ('offer_id', models.IntegerField(db_index=True)),
                ('sku', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('product_label_number', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('leadtime_days', models.IntegerField(null=True)),
                ('leadtime_stock', models.TextField(blank=True, default='[]', null=True)),
                ('status', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('offer_url', models.URLField(db_index=True)),
                ('stock_at_takealot', models.TextField(blank=True, db_index=True, default='[]', null=True)),
                ('stock_on_way', models.TextField(blank=True, default='[]', null=True)),
                ('total_stock_on_way', models.IntegerField(null=True)),
                ('stock_cover', models.TextField(blank=True, default='[]', null=True)),
                ('total_stock_cover', models.IntegerField(null=True)),
                ('sales_units', models.IntegerField(db_index=True)),
                ('sales_units_cpt', models.IntegerField()),
                ('sales_units_jhb', models.IntegerField()),
                ('stock_at_takealot_total', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField()),
                ('storage_fee_eligible', models.BooleanField(db_index=True, null=True)),
                ('discount', models.CharField(max_length=255)),
                ('discount_shown', models.BooleanField()),
                ('autoprice', models.BooleanField(db_index=True, default=False, null=True)),
                ('takealot_price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('best_price', models.BooleanField(db_index=True, default=False)),
                ('min_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Myoffers',
                'ordering': ['-sales_units'],
            },
        ),
    ]
