# Generated by Django 4.2.8 on 2024-01-15 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myoffers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.IntegerField()),
                ('order_id', models.IntegerField(db_index=True)),
                ('order_date', models.DateTimeField(db_index=True)),
                ('sale_status', models.CharField(db_index=True, max_length=255)),
                ('offer_id', models.IntegerField()),
                ('tsin', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('product_title', models.CharField(db_index=True, max_length=255)),
                ('takealot_url_mobi', models.URLField()),
                ('selling_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(db_index=True)),
                ('dc', models.CharField(db_index=True, max_length=255)),
                ('customer', models.CharField(db_index=True, max_length=255)),
                ('takealot_url', models.URLField()),
                ('success_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfillment_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courier_collection_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_ibt_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.IntegerField(db_index=True)),
                ('myoffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myoffers.myoffers')),
            ],
            options={
                'verbose_name_plural': 'Mysales',
                'ordering': ['-order_date'],
            },
        ),
    ]
